name: "Build and test our Eshop"

on:
  workflow_dispatch:
  push:

jobs:
  Install:
    runs-on: ubuntu-latest

    steps:
      - name: Git CheckOut
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOCKEN }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 10

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node_modules-

      - name: Install packages with npm
        run: |
          npm ci
# Build section
  Build: 
    needs: Install
    runs-on: ubuntu-latest

    steps:
      - name: Git CheckOut
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOCKEN }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 10
      
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Build
        run: |
          npm rebuild node-sass --force
          npm run build -- --colors
# End of build section
# Test section
  Test: 
    needs: Install
    runs-on: ubuntu-latest

    steps:
      - name: Git CheckOut
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOCKEN }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 10
      
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Run Tests
        run: |
          npm run test
# End of test section
#try to push
